### ISSUE TITLE
Authorization code expired

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-auth-fetcher#7]
Running dev-bundle against latest NSS with some debug statements in `node_modules/@solid/oidc-auth-manager/node_modules/@solid/oidc-op`, I'm seeing:
```sh
getting from backend 064b954843994809143f3e6afce99639
error HandledError: 400 Bad Request
    at TokenRequest.badRequest (/Users/michiel/gh/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/oidc-op/src/handlers/BaseRequest.js:249:17)
    at /Users/michiel/gh/solid/node-solid-server/node_modules/@solid/oidc-auth-manager/node_modules/@solid/oidc-op/src/handlers/TokenRequest.js:570:26 {
  handled: true,
  error: 'invalid_grant',
  error_description: 'Authorization code expired'
}

**Comment by michielbdejong** [comment]
ah this was because i hardcoded a token yesterday :)
